name: "@ebay/browserslist-config"
on: [push]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Execute tests
        run: yarn lint

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Execute tests
        run: yarn test
